### ISSUE TITLE
use ncclFp8E4M3 can't get correct result

### ISSUE THREAD

**Issue by kanghui0204** [Azure/msccl-executor-nccl#38]
Hi exports, I try to use this repo run fp8 allreduce , I run the allreduce on L40s(GPU sm 89), but after I intergate the allreduce into our program, and I get wrong result.

If I use allreduce sum , like this `NCCLCHECK(ncclAllReduce(inputs[0], outputs[0], size, ncclFp8E4M3, ncclSum, comm, stream));` , it will return tensor just like this:
 output.cpu() =  tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 0., 0., 0., 0., 0., 0., 0., 0.,0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

If I use allreduce max, it will return tensor just like this:
output.cpu() =  tensor([1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102,
        1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 1.0102, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])
It seems that only the first 16 of datas were written, but the values are still incorrect.

Is there any way to debug this? Or is there a setting that I haven't enabled?

**Comment by Andyli1007** [comment]
Kanghui：
   thanks a lot for reaching out to us. unfortunately, current msccl does not support for L40s. Our priority still focuses on the top GPU optimization, which including A/H100 and its successor, etc. so in this case, we strongly recommended for below two options.
1. Using the latest GPU types like A100/H100, for inference scenario, you can use ncv4/5 related VMs. 
2. Contribute to our open source, we will regularly review the PR to accept any valuable improvement for this project.

**Comment by kanghui0204** [comment]
OK , I see , perhaps I can try to read the source code. I have no more issues, and I will close this issue , thank you for your response.
