### ISSUE TITLE
How to run custom algos in single process?

### ISSUE THREAD

**Issue by TonyWu199** [Azure/msccl-executor-nccl#42]
Hi dear authors, I'd like to know how to run the custom algos in single process mode as mentioned in introduction.
```MSCCL-EXECUTOR-NCCL supports an arbitrary number of GPUs installed in a single node or across multiple nodes, and can be used in either single- or multi-process (e.g., MPI) applications.```

**Comment by yzygitzh** [comment]
Hi,

Sorry for the confusion. To run custom algos, only 1-GPU-1-process is supported for now. We'll revise the README.
